# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e7af85cf29243824a62841e0c654510591723ebfd6e87ccc7e98dc845b7ba1f520aad442574228383cd67720610c0e110386001d7cca70832e960413f1ad4af

test:
  secret_key_base: c1dcb231d00d99e6d192d5c8ed9a7161570c763416c65455244e981648ccfd741f6d9621f5116f50d7a6266049a34ad21bc0b686e2dde628913f40f6901c3b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
